# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr
script:
  - Rscript -e '(cov <- covr::package_coverage(quiet = F, clean = F))'
after_success:
