# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr@temp_lib

env:
  global:
    COVR_INSTALL_DIR=~/test
script:
  - Rscript -e '(cov <- covr::package_coverage(quiet = F, clean = F))'
  - find $COVR_INSTALL_DIR -name '*.fail' -print -exec cat '{}' \;
  - find $COVR_INSTALL_DIR -name '*.out' -print -exec cat '{}' \;
after_success:
